
- name: "=== Disco adicional ==="
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    instance_id:
    volume_size:
    region:
    

  tasks:

  - name:                  "=== Adicionando disco ==="
    ec2_vol:
      #aws_access_key: "{{ec2_access_key}}"
      #aws_secret_key: "{{ec2_secret_key}}"
      instance: "{{ instance_id }}"
      volume_size: "{{ volume_size }}"
      region: "{{ region }}"
