
- name: "Preparando Disco"
  hosts: all

  vars:
    device_name:

  tasks:

  - name: Criando filesystem ext4
    filesystem:
      fstype: ext4
      dev: "{{ device_name }}"
    become: true

  - name: Montando unidade em /mnt/dados
    mount:
      path: /mnt/dados
      src: "{{ device_name }}"
      fstype: ext4
      state: present
    become: true
